application: sqlformat-hrd
version: dev27
runtime: python27
api_version: 1
threadsafe: true

default_expiration: 7d  # This is good for images, which never change

handlers:

- url: /(robots.txt|favicon.ico|sitemap.xml)
  static_files: static/\1
  upload: static/(robots.txt|favicon.ico|sitemap.xml)

- url: /google7a062e78b56854c0.html
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static/(script.js|styles.css)
  static_files: static/\1
  upload: static/(script.js|styles.css)

- url: /static
  static_dir: static

- url: .*
  script: main.app

builtins:
- appstats: on

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?jinja2*

inbound_services:
- warmup

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: setuptools
  version: latest

