language: python
python: 2.7
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=pypy
before_install:
  - sudo apt-get install pypy
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
